title: Single Page Website
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"
description: >- 
  Template for a single-page website using GitHub-hosted static
  Jekyll pages and the Minimal-Mistakes remote-theme.
include:
  - _pages
plugins:
  - jekyll-include-cache
atom_feed:
  hide: true
